name: 🐛 Bug Report
description: Report a reproducible bug or regression
labels: [bug, needs triage]
body:
- type: checkboxes
  attributes:
    label: On what kind of device are you using this library?
    description: You may select more than one.
    options:
      - label: Android
      - label: iOS
      - label: Web
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **react-native**: 0.67.2
        - **@benjeau/react-native-draw**: 0.6.0
    value: |
        - OS:
        - react-native:
        - @benjeau/react-native-draw:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.